---
title: "Analysis"
author: "DBCA Kingston Spotlighting"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    fig_width: 10
    fig_height: 6
    code_folding: hide
    theme: lumen
  pdf_document:
    latex_engine: xelatex
  word_document: default
---
<!--  
This Rmd template provides an example workflow to access submissions and 
attachments of a given ODK Central form using its OData API and disseminate
data, attachments, and this report via CKAN or Google Drive.

You will need:
* An ODK Central form's OData Service URL (ending in .svc), accessed from the 
"Analyse using OData" button on the form submission tab.
* Username and password of an ODK Central webuser authorised to view this form.
* Optional: base URL and write-permitted API key for a CKAN instance.
* Optional: a Google account and the means to authenticate (e.g. phone for 2FA).
-->

<!--
Step 1: Setup ruODK, ckanr
Secrets are set as environment variables to keep them outside of this document. 
Read vignette "setup" for further information.
-->
<!-- 1a. Open the .Renviron file:  -->
```{r edit_renviron, echo=FALSE, eval=FALSE}
usethis::edit_r_environ()
```

<!-- 1b. Paste the following block using your own, working credentials:  -->
```{r paste_env_vars, echo=FALSE, eval=FALSE}
# ODK Central web user with read-permitted role on project
ODKC_UN="my@email.com"
ODKC_PW="my-odkc-password"

# CKAN user with permissions to create a dataset
CKAN_URL="https://demo.ckan.org"
CKAN_KEY="my-ckan-api-key"
```
<!-- 1c: Restart the R session to load these environment variables. -->

<!-- 
* Configure ODK Central base URL (url), project ID (pid), and form ID (fid) 
in one step using the OData Service URL.
* Paste your own Service URL over `svc="..."`.
* Paste your local timezone over `Australia/Perth`.
* Adjust `loc` to a local subfolder for downloaded attachments.
-->
```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
# Data wrangling
# library(stringr)
library(dplyr)
library(fs)
library(ruODK)

# Visualisation
library(skimr)
library(knitr)
library(reactable)

# Dissemination
library(readr)
# library(ckanr)
# library(googledrive)

# Spatial: see also vignette "spatial"
library(leaflet)
# library(rgeos)
# library(sf)

# Set ruODK defaults to an ODK Central form's OData Service URL


loc <- fs::path("media")
fs::dir_create(loc)
```


# Animals
<!-- 
  Summarise, analyse, visualise the tibble(s) data (, data_sub1, data_sub2) 
-->
```{r data_dl, message=FALSE}
ruODK::ru_setup(
  svc="https://odkc.dbca.wa.gov.au/v1/projects/6/forms/Spotlighting.svc",
  tz = "Australia/Perth", # your local timezone
  odkc_version = 1.0,     # your ODKC version, only needed if <=0.7
  verbose = TRUE)

data <- ruODK::odata_submission_get(local_dir = loc, wkt = TRUE)

ruODK::ru_setup(
  svc="https://odkc.dbca.wa.gov.au/v1/projects/6/forms/Spotlighting-Survey-Start.svc"
)
survey_start <- ruODK::odata_submission_get(local_dir = loc, wkt = TRUE)

ruODK::ru_setup(
  svc="https://odkc.dbca.wa.gov.au/v1/projects/6/forms/Spotlighting-Survey-End.svc"
)
survey_end <- ruODK::odata_submission_get(local_dir = loc, wkt = TRUE)
```

## Data overview
```{r animals_overview}
skimr::skim(data)
dplyr::glimpse(data)
```

## Data
A full table of data.
```{r animals_table}
reactable::reactable(data, filterable = TRUE, sortable = TRUE, searchable = TRUE)
```

## Map
```{r animals_map}
leaflet::leaflet(width = 800, height = 600) %>%
  leaflet::addProviderTiles("OpenStreetMap.Mapnik", group = "Place names") %>%
  leaflet::addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  leaflet::clearBounds() %>%
  leaflet::addAwesomeMarkers(
    data = data,
    group = "Animals",
    # 
    # # Adjust to your coordinate field names
    # 
    lng = ~location_group_location_longitude, 
    lat = ~location_group_location_latitude, 
    icon = leaflet::makeAwesomeIcon(text = "A", markerColor = "red"),
    # 
    # # With your own names(data)
    # 
    label = ~ glue::glue("{encounter_start_datetime} ",
                         "{animal_details_number_of_individuals} ",
                         "{animal_details_species}"),
    popup = ~ glue::glue(
      "<h3>{animal_details_number_of_individuals} {animal_details_species}</h3>",
      "Seen on {encounter_start_datetime}<br/>",
      # "Reporter {username}<br/>",
      "Account {system_submitter_name} on {device_id}<br/>",
      "Distance odometer: {location_group_distance_odometer}m<br/>",
      
      "<h5>Animal</h5>",
      "Species ID: {animal_details_species_id_certainty}<br/>",
      "Distance to animal: {animal_details_distance_to_animal_metres}<br/>",
      "Bearing to road: {animal_details_bearing_to_road_degrees}<br/>",
      "Bearing to animal: {animal_details_bearing_to_animal_degrees}<br/>",
      "Side: {animal_details_side}<br/>",
      
      "<h5>Surroundings</h5>",
      "Tree: {surroundings_tree_species} / {surroundings_tree_species_other}<br/>",
      "Animal sat on: {surroundings_substrate_under_animal}",
      " {surroundings_animal_height_above_ground_estimate_metres} m above ground",
      " doing {surroundings_animal_activities}<br/>",
      "Site type: {surroundings_site_type}<br/>",
      "Notes: {surroundings_notes}<br/>"
    ),
    # 
    # # If there are many submissions, cluster markers for performance:
    # clusterOptions = leaflet::markerClusterOptions()
  ) %>%
  leaflet::addAwesomeMarkers(
    data = survey_start,
    group = "Survey Start",
    # 
    # # Adjust to your coordinate field names
    # 
    lng = ~location_group_location_longitude, 
    lat = ~location_group_location_latitude, 
    icon = leaflet::makeAwesomeIcon(text = "S", markerColor = "green"),
    # 
    # # With your own names(data)
    # 
    label = ~ glue::glue("{survey_start_datetime}",
                         " {location_group_transect_name} start"),
    popup = ~ glue::glue(
      "<h3>Survey start {survey_start_datetime} {location_group_transect_name}</h3>",
      "Started on {survey_start_datetime}<br/>",
      # "Reporter {username}<br/>",
      "Account {system_submitter_name} on {device_id}<br/>",
      
      "<h5>Team</h5>",
      "Observer left: {team_observer_left}<br/>",
      "Observer right: {team_observer_right}<br/>",
      "Driver: {team_driver}<br/>",
      "Recorder: {team_recorder}<br/>",
      
      "<h5>Methodology</h5>",
      "Distance measured by : {methods_distance_measure}<br/>",
      "No spotlights: {methods_number_of_spotlights}<br/>",
      "Comments: {methods_comments}<br/>",
      
      "<h5>Climate and Environment</h5>",
      "Air temp: {climate_air_temperature} deg C<br/>",
      "Wind speed: {climate_wind_speed_kmh} km/h<br/>",
      "Precipitation: {climate_precipitation}<br/>",
      "Moon phase: {climate_moon_phase} of 8<br/>",
      "Cloud cover: {climate_cloud_cover} of 8<br/>"
      
    ),
    # 
    # # If there are many submissions, cluster markers for performance:
    # clusterOptions = leaflet::markerClusterOptions()
  ) %>%
  leaflet::addAwesomeMarkers(
    data = survey_end,
    group = "Survey End",
    # 
    # # Adjust to your coordinate field names
    # 
    lng = ~location_group_location_longitude, 
    lat = ~location_group_location_latitude, 
    icon = leaflet::makeAwesomeIcon(text = "E", markerColor = "blue"),
    # 
    # # With your own names(data)
    # 
    label = ~ glue::glue("{survey_end_datetime} end"),
    popup = ~ glue::glue(
      "<h3>Survey end {survey_end_datetime}</h3>",
      "Started on {survey_end_datetime}<br/>",
      # "Reporter {username}<br/>",
      "Account {system_submitter_name} on {device_id}<br/>",
      
      "<h5>Methodology</h5>",
      "GPS reference point: {location_group_gps_reference_point}<br/>",
      "Avg vehicle speed: {methods_average_vehicle_speed_kmh} km/h<br/>",
      "Comments: {methods_methodology_comments}<br/>",
      
      "<h5>Climate and Environment</h5>",
      "Air temp: {climate_air_temperature} deg C<br/>",
      "Wind speed: {climate_wind_speed_kmh} km/h<br/>",
      "Precipitation: {climate_precipitation}<br/>",
      "Moon phase: {climate_moon_phase} of 8<br/>",
      "Cloud cover: {climate_cloud_cover} of 8<br/>"
      
    ),
    # 
    # # If there are many submissions, cluster markers for performance:
    # clusterOptions = leaflet::markerClusterOptions()
  ) %>%
  leaflet::addLayersControl(
    baseGroups = c("Place names", "Aerial"),
    overlayGroups = c("Animals", "Survey Start", "Survey End"),
    options = leaflet::layersControlOptions(collapsed = FALSE)
  )
```

# Surveys

## Start points
```{r svy_start_table}
reactable::reactable(survey_start, filterable = TRUE, sortable = TRUE, searchable = TRUE)
```

## End points
```{r svy_end_table}
reactable::reactable(survey_end, filterable = TRUE, sortable = TRUE, searchable = TRUE)
```


# Export
<!--
The form submissions are now extracted and visualised. What's next:

* Save data to local files (e.g. CSV).
* Compile report (e.g. to HTML).
* Compress all outputs as ZIP.
* Upload these artifacts to a CKAN data catalogue.
* Upload same artifacts to Google Drive.

Notes: 

* Generate the HTML report once off without the next chunk (`eval=F`), 
as the chunk refers to the rendered output file (HTML) before the file is 
created initially.
* Run report always twice to generate (run 1) and upload (run 2) the latest HTML.
-->
```{r data_export}
#------------------------------------------------------------------------------#
# Prepare report and products as local files
#
# rep_fn <- "my_report.html" # The file name you save this template under
# data_fn <- here::here(loc, "data.csv") %>% as.character()           # Main data
# data_sub1_fn <- here::here(loc, "data_sub1.csv") %>% as.character() # Sub table 1
# data_sub2_fn <- here::here(loc, "data_sub2.csv") %>% as.character() # Sub table 2
# zip_fn <- "products.zip" # Attachments as one zip file (top level)

# Write data tbls to CSV files
readr::write_csv(data, path = "inst/extdata/export/animals.csv")
readr::write_csv(survey_start, path = "inst/extdata/export/survey_start.csv")
readr::write_csv(survey_end, path = "inst/extdata/export/survey_end.csv")

# Compress everything into `zip_fn`, retain relative path to `loc`
# zip(zipfile = zip_fn, files = fs::dir_ls(loc))

#------------------------------------------------------------------------------#
# CKAN
#
# Upload to a CKAN data catalogue (needs url and API key of a write permitted user)
# See ROpenSci package ckanr
ckanr::ckanr_setup(url = Sys.getenv("CKAN_URL"), key = Sys.getenv("CKAN_API_KEY"))
# ckan_ds_name <- "my-ckan-dataset-slug"
# 
# # Run once to create resources on an existing dataset, then comment out
# d <- ckanr::package_show(ckan_ds_name)
# res_data_main <- ckanr::resource_create(
#   package_id = d$id, name="Main data", upload = data_fn)
# res_data_sub1 <- ckanr::resource_create(
#   package_id = d$id, name="Nested data table 1", upload = data_sub1_fn)
# res_data_sub2 <- ckanr::resource_create(
#   package_id = d$id, name="Nested data table 2", upload = data_sub2_fn)
# # add remaining tables
# if (fs::file_exists(rep_fn)){
# res_report <- ckanr::resource_create(
#   package_id = d$id, name="Data report", upload = rep_fn)
# }
# 
# if (fs::file_exists(zip_fn)){
# res_zip <- ckanr::resource_create(
#   package_id = d$id, name="All data and attachments", upload = zip_fn)
# }
# # Paste res_data_main$id over RID and keep here, repeat for each resource
r <- ckanr::resource_update("89054b15-14fb-4d75-8c92-e49e9bcf2f8b", path = "analysis.html")
# r <- ckanr::resource_update(res_data_sub1$id, path = data_sub1_fn)
# r <- ckanr::resource_update(res_data_sub2$id, path = data_sub2_fn)
# if (fs::file_exists(rep_fn)){
#   r <- ckanr::resource_update(res_report$id, path = rep_fn)
# }
# r <- ckanr::resource_update(res_zip$id, path = zip_fn)
# 
# #------------------------------------------------------------------------------#
# # Google Drive
# #
# # Run once per machine, then comment out:
# googledrive::drive_auth(use_oob = TRUE)
# 
# # Upload to Google Drive
# gd_fn <- "My Google Drive folder name"
# googledrive::drive_ls(gd_fn) %>% googledrive::drive_rm(.)  # Wipe older outputs
# if (fs::file_exists(rep_fn)){
#   googledrive::drive_upload(rep_fn, path=rep_fn)             # Report as HTML
# }
# googledrive::drive_upload(data_fn, path=data_fn)           # Main data as CSV
# googledrive::drive_upload(data_sub1_fn, path=data_sub1_fn) # Sub table 1 as CSV
# googledrive::drive_upload(data_sub2_fn, path=data_sub2_fn) # Sub table 2 as CSV
# googledrive::drive_upload(zip_fn, path=zip_fn)             # All outputs as ZIP
```
